// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: generations.sql

package database

import (
	"context"
)

const createGeneration = `-- name: CreateGeneration :one
INSERT INTO generations (id, name, region_name)
VALUES ($1, $2, $3)
ON CONFLICT (id) DO NOTHING
RETURNING id, name, region_name
`

type CreateGenerationParams struct {
	ID         int32  `json:"id"`
	Name       string `json:"name"`
	RegionName string `json:"region_name"`
}

func (q *Queries) CreateGeneration(ctx context.Context, arg CreateGenerationParams) (Generation, error) {
	row := q.db.QueryRowContext(ctx, createGeneration, arg.ID, arg.Name, arg.RegionName)
	var i Generation
	err := row.Scan(&i.ID, &i.Name, &i.RegionName)
	return i, err
}

const listGenerations = `-- name: ListGenerations :many
SELECT id, name, region_name FROM generations
ORDER BY id
`

func (q *Queries) ListGenerations(ctx context.Context) ([]Generation, error) {
	rows, err := q.db.QueryContext(ctx, listGenerations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Generation
	for rows.Next() {
		var i Generation
		if err := rows.Scan(&i.ID, &i.Name, &i.RegionName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
