// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
)

type Ability struct {
	ID          int32  `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

type Evolution struct {
	ID              int32          `json:"id"`
	FromSpeciesID   int32          `json:"from_species_id"`
	ToSpeciesID     int32          `json:"to_species_id"`
	Trigger         string         `json:"trigger"`
	MinLevel        sql.NullInt32  `json:"min_level"`
	ItemName        sql.NullString `json:"item_name"`
	HeldItemName    sql.NullString `json:"held_item_name"`
	TimeOfDay       sql.NullString `json:"time_of_day"`
	KnownMoveTypeID sql.NullInt32  `json:"known_move_type_id"`
}

type Generation struct {
	ID         int32  `json:"id"`
	Name       string `json:"name"`
	RegionName string `json:"region_name"`
}

type Move struct {
	ID          int32         `json:"id"`
	Name        string        `json:"name"`
	TypeID      sql.NullInt32 `json:"type_id"`
	Power       sql.NullInt32 `json:"power"`
	Accuracy    sql.NullInt32 `json:"accuracy"`
	Pp          int32         `json:"pp"`
	DamageClass string        `json:"damage_class"`
	Description string        `json:"description"`
}

type Pokemon struct {
	ID        int32  `json:"id"`
	SpeciesID int32  `json:"species_id"`
	Name      string `json:"name"`
	Height    int32  `json:"height"`
	Weight    int32  `json:"weight"`
	IsDefault bool   `json:"is_default"`
	SpriteUrl string `json:"sprite_url"`
}

type PokemonAbility struct {
	PokemonID int32 `json:"pokemon_id"`
	AbilityID int32 `json:"ability_id"`
	IsHidden  bool  `json:"is_hidden"`
}

type PokemonMove struct {
	PokemonID    int32  `json:"pokemon_id"`
	MoveID       int32  `json:"move_id"`
	LearnMethod  string `json:"learn_method"`
	LevelLearned int32  `json:"level_learned"`
}

type PokemonType struct {
	PokemonID int32         `json:"pokemon_id"`
	TypeID    sql.NullInt32 `json:"type_id"`
	Slot      int32         `json:"slot"`
}

type Species struct {
	ID            int32         `json:"id"`
	Name          string        `json:"name"`
	GenerationID  int32         `json:"generation_id"`
	PokedexOrder  sql.NullInt32 `json:"pokedex_order"`
	Description   string        `json:"description"`
	BaseHappiness sql.NullInt32 `json:"base_happiness"`
	CaptureRate   sql.NullInt32 `json:"capture_rate"`
}

type Type struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}
