// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: types.sql

package database

import (
	"context"
)

const createType = `-- name: CreateType :one
INSERT INTO types (id, name)
VALUES ($1, $2)
ON CONFLICT (id) DO UPDATE
SET name = EXCLUDED.name
RETURNING id, name
`

type CreateTypeParams struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) CreateType(ctx context.Context, arg CreateTypeParams) (Type, error) {
	row := q.db.QueryRowContext(ctx, createType, arg.ID, arg.Name)
	var i Type
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const listTypes = `-- name: ListTypes :many
SELECT id, name FROM types
ORDER BY id
`

func (q *Queries) ListTypes(ctx context.Context) ([]Type, error) {
	rows, err := q.db.QueryContext(ctx, listTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Type
	for rows.Next() {
		var i Type
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
